### ISSUE TITLE
Vehicle Type Filter

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/nyc-crash-mapper#104]
Over in https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/issues/22, we started pulling in and allocating Vehicle Type data. Now we need to add a filter for it.

Basically this:
![image](https://user-images.githubusercontent.com/1423200/72103720-a58f9380-32de-11ea-8ce0-6db1cea1b5be.png)

In context of the whole sidebar on the map:
![image](https://user-images.githubusercontent.com/1423200/72103772-c35cf880-32de-11ea-97d7-0ae1328f2d47.png)

It fits between current "Filter by Type" and "Data", and then rename the label on "Filter by Type" to "Filter by Crash Type"

**Comment by gregallensworth** [comment]
Here is the panel, and its filtering behavior for the statistics and the map. This is currently implemented in the `gda-vehiclefilter` branch.

**SCREENSHOTS*

![image](https://user-images.githubusercontent.com/3117633/72114316-fe1f5a80-32f7-11ea-9b9b-a850197f0526.png)

![image](https://user-images.githubusercontent.com/3117633/72114348-1a22fc00-32f8-11ea-9e9d-e91118bd569b.png)

**BEHAVIOR NOTES**

When no options are selected, no vehicle-involvement filter is applied.

Like the crash type (injury/fatality) filter, this new vehicle-involvement filter is an OR clause. That is to say, adding options will expand the range of results. *Crashes which involve a motorcycle AND/OR involve a bicycle AND/OR involve a scooter*.

That's as opposed to ANDing them, by which adding options will narrow the range of results to find combinations. "Crashes involving a bicycle AND a car*. I could see an argument for preferring this behavior in order to find combinations. Of course, beyond 2 selections one approaches very specific and very few matches, e.g. *Crashes involving a bicycle and a car and a motorcycle*.

**Comment by danrademacher** [comment]
This is working well locally for me. I did add the word "Type" to the Vehicle Type panel title.

I do notice that the behavior of the Crash Type and Vehicle Type panels is slightly different, where the Crash Type is a true set of toggle, which load in the "ON" position and if you turn them all off, blank map.

Vehicle Type loads in the OFF position and as you describe, no filter is applied:
![image](https://user-images.githubusercontent.com/1423200/72116006-b996bd80-32fd-11ea-87eb-b6f20d109e63.png)

While both approaches have their merits, since the Crash Type has been in the app and set the pattern, ideally we  would make the Vehicle Type panel work the same way, so the loaded state would look like this:
![image](https://user-images.githubusercontent.com/1423200/72116075-e5b23e80-32fd-11ea-8ba3-78a6e98b5134.png)

**Comment by gregallensworth** [comment]
⬆️  Per https://github.com/GreenInfo-Network/nyc-crash-mapper/issues/104#issuecomment-572820328 the Vehicle Type panel is now all-on by default, so applying a filter of "any of these 8" by default.

Note that at present *23,410 crash entries* in the database which are false for all 8 flags, so would now be omitted from this default view. This may cause some discrepancies in a detailed count of records of CrashMapper vs Socrata. I will bring that up in https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/issues/22 for further discussion at the ETL level.

**Comment by gregallensworth** [comment]
The data cleanup in https://github.com/GreenInfo-Network/nyc-crash-mapper-etl-script/issues/22 went well, and now we have 22,500-ish records with an empty `vehicle_type` array.

Per discussion, let's rework the Other button as "Other / Unspecified" The SQL clause would be `hasvehicle_other = true OR no to the other 7`

This would effectively "fill in the blank" of crashes with unspecified vehicle types, but would leave the underlying data intact for later evaluation, re-classification, or a change in behavior.

**Comment by danrademacher** [comment]
Reviewed and ready to deploy, but holding until matching filter in Chart view is also functional. (https://github.com/GreenInfo-Network/nyc-crash-mapper-chart-view/issues/108)

**Comment by gregallensworth** [comment]
e0dabcc -- The Trend, Compare, and Ranks hyperlinks at the top, now include the vehicle-type URL params. These match the format used in https://github.com/GreenInfo-Network/nyc-crash-mapper-chart-view/issues/108 and are confirmed to correctly load all three chart views with the same vehicle filter selected.

This is for the `gda-vehiclefilter` branch. Let's give it a test, and see whether #104 and https://github.com/GreenInfo-Network/nyc-crash-mapper-chart-view/issues/108 are working, so they may be deployed and closed.

**Comment by gregallensworth** [comment]
Deployed.
